import fs from 'node:fs';
import assert from 'node:assert/strict';
const [sourceRoot, importFile] = process.argv.slice(2);
if (!sourceRoot || !importFile) throw new Error('Usage: node test_labmate.mjs LABMATE_CHECKOUT GENERATED_EXAMPLE_IMPORT');
const source = fs.readFileSync(sourceRoot + '/src/lib/backup.js', 'utf8').replace("import db from './db.js';", 'const db = globalThis.testDB;');
const store = new Map([['labmate_customProtocols', JSON.stringify([{id:'existing-protocol',name:'Existing'}])], ['lang', 'zh']]);
globalThis.localStorage = {getItem: k => store.get(k) ?? null, setItem: (k,v) => store.set(k,v)};
let saved;
globalThis.testDB = {customProtocols:{clear:async()=>{},bulkPut:async rows=>{saved=rows;}}};
const {importBackup} = await import('data:text/javascript;base64,' + Buffer.from(source).toString('base64'));
const normalizeSource = fs.readFileSync(sourceRoot + '/src/lib/protocolImport.js', 'utf8');
const {toProcedureSteps,toReagents} = await import('data:text/javascript;base64,' + Buffer.from(normalizeSource).toString('base64'));
const content = fs.readFileSync(importFile,'utf8');
await importBackup(content);
await Promise.resolve();
const recipes = JSON.parse(store.get('labmate_customProtocols'));
assert.equal(recipes.length,2);
assert.equal(recipes[0].name,'Existing');
assert.equal(store.get('lang'),'zh');
assert.equal(saved.length,2);
const steps = toProcedureSteps(recipes[1]);
assert.equal(steps.length,2);
assert.equal(steps[0].completed,false);
assert.match(steps[0].stepText,/Teaching example, instruction 1/);
assert.equal(toReagents(recipes[1])[0].name,'Example input table');
await importBackup(content);
assert.equal(JSON.parse(store.get('labmate_customProtocols')).length,2);
console.log('PASS: actual Labmate importer merges protocol, preserves existing data, converts steps and replaces same ID.');
